### ISSUE TITLE
use truffle for contract compilation

### ISSUE THREAD

**Issue by anoff** [OpenMined/PySonar#1]
Currently `py-solc` is used but `truffle` might be the better choice for overall tooling

**Comment by kirtanechiron** [comment]
I second that motion. So far things seem to be working except solc. The notebook in PySonar gets through the imports, but then under "Setting up the Experiment" it returns an error: 
FileNotFoundError: [Errno 2] No such file or directory: 'solc'

**Comment by iamtrask** [comment]
Yeah, solc is a pain to install. We've split out this repo and Sonar into two separate ones. This repo will be the Python adapter allowing you to make calls (which will ultimately become the data science library that makes calls to the blockchain). Sonar itself will be a truffle project (just pushed the "truffle init" state). 

Going to go ahead and close this since we've decided to change direction. Great recommendations guys!
